import UserInfos from "../models/user";
import bcrypt from "bcrypt";
import TokenAuth from "../helpers/tokenAuth"
import BookInfos from "../models/book";
import TourInfos from "../models/tours";


class UserController{
      
    //create user in db
    /** 
        * Generate
        * @static
        * @param {req,res} Req object
        * @memberof UserController
        * @return {String} Response
        */

    static async createUser(req,res){

       const hashPassword= bcrypt.hashSync(req.body.password,10)
       req.body.password =hashPassword;
        const user= await UserInfos.create(req.body); //this function return generated data //req.body ,request data from body in postman

        if(!user){
            return res.status(404).json({error:"user not registered"})
        } 

        return res
        .status(200)
        .json({message:"User created successfully" , data: user});

    }
    //get all users
    static async getAllUsers(req,res){ //
        const users= await UserInfos.find(); // return generated data

        if(!users){
            return res.status(404).json({error:"no users registered"})
        }

        return res
        .status(200)
        .json({message:"Successfully retrieved users" , data: users});

    }
     //getting a specific user
    static async getOneUser(req,res){

      const user= await UserInfos.findById(req.params.id); //this functions return the data yabonye according to the id given
       
      if(!user){
          return res.status(404).json({error:"user not found"});
      }
      return res
      .status(200)
      .json({message:"user found successful", data:user})

    }
    // delete a user
    static async deleteOneUser(req,res){

        const user= await UserInfos.findByIdAndDelete(req.params.id); //this functions return the data yabonye according to the id given
         
        if(!user){
            return res.status(404).json({error:"user not found"});
        }
        return res
        .status(200)
        .json({message:"user deleted successful", data:user})
  
      }
      // login function
      static async userLogin(req,res){
          const user = await UserInfos.findOne({email:req.body.email});

          if(!user){
              return res.status(404).json({error:"user not Found! Kindly register first"}) // f(x) which checks/or compare  data hashed  if the writen psw and the hashed psw are the same
          }
          if(bcrypt.compareSync(req.body.password,user.password)){
            user.password=null;
            const token = TokenAuth.tokenGenerator({user:user});
            return res.status(200).json({message:"Succefully logged in", token: token});
            
          }
          return res.status(400).json({error:"Password is wrong"})
      }

      // Booking function

      static async bookTour(req,res){
          const bookData= {
            user: req.user._id, // the id with under score is the id generated by mongodb
            tour:req.params.id //
        };
          const book = await BookInfos.create(bookData);

          const tour = await TourInfos.findById(req.params.id);
          const tourSeats =tour.seats-1;
          await TourInfos.findByIdAndUpdate(req.params.id,{seats: tourSeats});

          if(!book){
              return res.status(404)
              .json ({error:"failed to book"});
          }
          return res.status(200).json({message:"Booked succcesfully", data:book});

      }
      // getAll Booking Tours

      static async getAllBookingsTours(req,res){
    
        const books = await BookInfos.find();

        if(!books){
            return res
            .status(404)
            .json ({error:"No bookings Registered"});
        }
        return res.status(200).json({message:"All  Bookings succesfully viewed  ", data:books});

    }
    //

    static async getAllBookingByTourId(req,res){
        const books =await BookInfos.find({tour:req.params.id});

        if (!books){
            return res.status(404).json({error:"Success"});
        }
        return res.status(200).json({message:"All  Bookings by Tour Id succesfully viewed  ", data:books});

    }
    static async getAllBookingByUserId(req,res){
        const books =await BookInfos.find({user:req.user.id});

        if (!books){
            return res.status(404).json({error:"Success"});
        }
        return res.status(200).json({message:"All  Bookings by user Id succesfully viewed  ", data:books});

    }
}
export default UserController;

// controller is the one directlly connected on database
// controller is where all the action are done
//is a class beacuse its hold different function